version: "3.7"

services:
  backend:
    build:
      context: .
      dockerfile: back-end/Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    networks:
      - app-network
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: .
      dockerfile: front-end/Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
